# permissions for end users to view installers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installer-viewer-role
rules:
- apiGroups:
  - installer.devtron.ai
  resources:
  - installers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - installer.devtron.ai
  resources:
  - installers/status
  verbs:
  - get
