# permissions for end users to edit installers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installer-editor-role
rules:
- apiGroups:
  - installer.devtron.ai
  resources:
  - installers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - installer.devtron.ai
  resources:
  - installers/status
  verbs:
  - get
